### ISSUE TITLE
 invalid region "steam"

### ISSUE THREAD

**Issue by trololo151** [kuper-adrian/statg-bot#17]
Hello! Pubg changed something, I do not know, now Error Error is issued
invalid region "steam"

**Comment by trololo151** [comment]
Are you here ?

**Comment by kuper-adrian** [comment]
hey trololo151,

yes I'm still here 😅Sorry for the late response, I was preoccupied with some other projects the last few weeks.

I get the same error message. It looks like Pubg Corp did some changes to the API again. Will look into this

Edit: Ok, found the bug. It's related to all pc-regions being grouped to the new region "steam" (or "kakao" for South Korea). Give me some time to fix this

**Comment by kuper-adrian** [comment]
Should work again. Would be cool if could answer if it does for you as well, @trololo151

**Comment by trololo151** [comment]
did not help (

**Comment by trololo151** [comment]
wrong season statistics zeros
```
 Handling stats command!
2018-12-19 03:45:21 [debug]:    Successfully fetched seasons data!
2018-12-19 03:45:21 [debug]:    Id of current season: division.bro.official.pc-2018-02
2018-12-19 03:45:21 [debug]:    Fetching stats...
2018-12-19 03:45:22 [debug]:    Successfully fetched stats!
2018-12-19 03:45:22 [debug]:    onResolved
```

**Comment by kuper-adrian** [comment]
Did you run `npm install` to update all dependecies? Keep in mind that a new season started with the Vikendi patch today. `!statg stats` displays seasons statistics, so if you haven't played since the update those stats beeing all zeros could be correct.

Btw: I plan a `statg lifetime-stats` command some time soon in order to display season-spanning stats.
