### ISSUE TITLE
Does not correctly print avgStats.avgKills

### ISSUE THREAD

**Issue by trololo151** [kuper-adrian/statg-bot#3]
bot and site show different statistics
pubg.op.gg

**Comment by trololo151** [comment]
Does not correctly consider cd for this line
result.avgKills = result.kills / result.roundsPlayed;

**Comment by kuper-adrian** [comment]
Sry for the late response. 

Could you provide an example/username or maybe screenshots of the problem? My own stats don't differ from the pubg.op.gg results so its hard for me to find the cause.

**Comment by trololo151** [comment]
![image](https://user-images.githubusercontent.com/17259203/44959611-d43b7400-af0a-11e8-839e-a2f7b9969de8.png)
![image](https://user-images.githubusercontent.com/17259203/44959613-db628200-af0a-11e8-9116-9dd01969b717.png)
In your case, cd is considered as damage / matches, and you need damage / death

**Comment by kuper-adrian** [comment]
After checking the numbers I noticed the following:

The formula statg uses at the moment is
```javascript
avgKills = kills / roundsPlayed
```
This calculation is somewhat off, because you don't necessarily die every single game.

pubg.op.gg on the other hand seems to be using the following formula
```javascript
avgKills = kills / (roundsPlayed - wins)
```
In my opinion this value is also not 100% correct, since you can win a game after you died (at least if you are playing duos or squad). But I will use this formula to be consistent with pubg.op.gg.

Thanks for reporting this issue.

**Comment by trololo151** [comment]
does not correctly show everything exactly
